package codcivic.vinebusu.dto;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRIP_DTO".
 */
@Entity
public class TripDto {

    @Id
    private String tripId;
    private String serviceId;
    private String tripHeadsign;
    private String tripShortName;

    @Generated
    public TripDto() {
    }

    public TripDto(String tripId) {
        this.tripId = tripId;
    }

    @Generated
    public TripDto(String tripId, String serviceId, String tripHeadsign, String tripShortName) {
        this.tripId = tripId;
        this.serviceId = serviceId;
        this.tripHeadsign = tripHeadsign;
        this.tripShortName = tripShortName;
    }

    public String getTripId() {
        return tripId;
    }

    public void setTripId(String tripId) {
        this.tripId = tripId;
    }

    public String getServiceId() {
        return serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public String getTripHeadsign() {
        return tripHeadsign;
    }

    public void setTripHeadsign(String tripHeadsign) {
        this.tripHeadsign = tripHeadsign;
    }

    public String getTripShortName() {
        return tripShortName;
    }

    public void setTripShortName(String tripShortName) {
        this.tripShortName = tripShortName;
    }

}
