package rocod.vinebusu.dto;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ROUTE_DTO".
 */
@Entity
public class RouteDto {
    private String name;

    @Generated(hash = 1599422008)
    public RouteDto() {
    }

    @Generated(hash = 1745196078)
    public RouteDto(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
